name: Infra - build and test

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/build-infra.yml"

jobs:
  build-and-test-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: |
            infra/package-lock.json

      - name: Install infra dependencies
        run: npm ci

      - name: Lint
        run: npx eslint .

      - name: Code style
        run: npx prettier --check .

      - name: Test infra
        run: npm run test
