name: Infra - update almost all dependencies

on:
  workflow_dispatch:

jobs:
  update-infra-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 4
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: |
            infra/pnpm-lock.json

      - name: Install infra dependencies
        run: pnpm install

      - name: Create working branch
        run: |
          git checkout -b infra-deps

      - name: Update dependencies
        run: |
          pnpm run npm-check-updates -u --reject @types/node --install always

      - name: Test
        run: |
          pnpm run test

      - name: Commit changes
        run: |
          git config --local user.email "pelaakso@users.noreply.github.com"
          git config --local user.name "pelaakso"
          git commit -a -m "Deps/infra: update infra dependencies"

      - name: Push changes
        run: |
          git push origin infra-deps

      - name: Create pull request
        run: |
          gh pr create --base main --head infra-deps --title "Deps/infra: update infra dependencies" --body "Update all dependencies, exluding node types"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
